#!/usr/bin/env bash
# Copy the prebuild-generated QVAC worker bundle to a build host.
#
# THE PROBLEM IT SOLVES. node_modules/@qvac/sdk/dist/worker.mobile.bundle.js is a
# ~9 MB file that `expo prebuild` GENERATES into node_modules (alongside the qvac/
# dir it also writes). It is not in the npm tarball, so `npm install` on another
# machine does not produce it. Every iOS build path rsyncs the repo to the Mac Mini
# with --exclude='node_modules', and prebuild only ever runs on the Linux box, so
# the Mac never had it: builds there produced an app whose
# require("@qvac/sdk/worker.mobile.bundle") failed at RUNTIME with "Failed to load
# mobile worker bundle", i.e. the on-device AI could not start at all.
#
# The Xcode build succeeds either way, which is what made this invisible: nothing
# in the release chain failed. Verified 2026-07-26 on the Simulator - without this
# file the harness aborts with that exact error, with it the model loads.
#
# Usage: ./scripts/sync-qvac-worker.sh <host> <remote-repo-path> [rsync-path]

set -euo pipefail

HOST="${1:?usage: sync-qvac-worker.sh <host> <remote-repo-path> [rsync-path]}"
REMOTE="${2:?usage: sync-qvac-worker.sh <host> <remote-repo-path> [rsync-path]}"
RSYNC_PATH="${3:-}"

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
REL="node_modules/@qvac/sdk/dist/worker.mobile.bundle.js"
SRC="$REPO_ROOT/$REL"

if [ ! -f "$SRC" ]; then
  echo "Error: $REL is missing locally." >&2
  echo "  It is generated by 'expo prebuild'. Run 'npx expo prebuild' (or a full" >&2
  echo "  release, which does) and try again - do NOT ship an iOS build without it," >&2
  echo "  the on-device AI will fail to start on every device." >&2
  exit 1
fi

echo "    Syncing $REL ($(du -h "$SRC" | cut -f1)) to $HOST"
if [ -n "$RSYNC_PATH" ]; then
  rsync -az --rsync-path="$RSYNC_PATH" "$SRC" "$HOST:$REMOTE/$REL"
else
  rsync -az "$SRC" "$HOST:$REMOTE/$REL"
fi
